[package]
name = "warp-engine"
version = "0.1.0"
authors = ["Theo Dedeken <theo.dedeken@telenet.be>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.11"
stdweb = "0.4.6"
glenum-bindgen = { path = "../glenum-bindgen" }
webgl2-bindgen = { path = "../webgl2-bindgen" }
